### ISSUE TITLE
securekey.heroku.com is currently unable to handle this request

### ISSUE THREAD

**Issue by ForbesLindesay** [will/securekey#5]
When I click the "Secure Key :: Secure" link under "Resources" for my Heorku Drone with Secure Key configured, I get the following error:

```
This page isn’t working
securekey.heroku.com is currently unable to handle this request.
HTTP ERROR 501
```

**Comment by will** [comment]
This app doesn't support the heroku sso. I don’t think I have it turned on in my addons-manifest.json, but maybe something to flipped over the years. I'll look into it, thanks.
